### ISSUE TITLE
#4 の発表内容どうしますか？

### ISSUE THREAD

**Issue by hururtoriya** [PRMLSeminar/prml-wakaranu#2]
僕は前回発表できなかったクラスタリング関連の事についてしゃべります。

**Comment by HiroyoshiIto** [comment]
@hururtoriya 次回LDA（Latent Dirichlet Allocation）について情報提供します．

**Comment by hururtoriya** [comment]
@HiroyoshiIto ありがとうございます!! :+1: 
自然言語処理の分野も面白いと思うので丁寧なイントロダクションがあるとありがたいです！
:heart_eyes::heart_eyes::heart_eyes::heart_eyes:

**Comment by hururtoriya** [comment]
僕はノンパラメトリック法と各種クラスタリング手法についてまとめた発表をする予定です。

**Comment by kein1592** [comment]
吉川です(イベントの登録はTwitterの方でやりました)
参加申し込みが遅くなって申し訳ありません。
ちょうど線形回帰をPRMLのほうでされていたためそれに関連するトピックについて発表します。
具体的には、ロバスト推定の一手法であるRANSACについて発表したいです。

**Comment by hururtoriya** [comment]
@kein1592 :+1: 良いですね。発表ありがとうございます!!
時間としては20分程度で説明してくださると助かります :smile:
