### ISSUE TITLE
KLダイバージェンスについて

### ISSUE THREAD

**Issue by getumen** [PRMLSeminar/prml-wakaranu#3]
２回目の勉強会でKLダイバージェンスについて分かったことがあればとのことだったので

KLダイバージェンスは情報幾何の分野で距離を表しているそうです。
確率ではユークリッド空間のような距離は定義できないので、使うようです。
確率モデルP_1,P_2のどちらからデータが生成されるのかを識別する識別噐を作るときに、
KLダイバージェンスを最大化して求める、といったことに使うようです。

自分の理解が間違っている可能性があるので、参考までに

nkzt

**Comment by hururtoriya** [comment]
@getumen なるほど、ありがとうございます :+1: 
ふむふむ。確かに確率空間での距離の存在がないと色々と不便そうですね。
参考情報ありがたいです

**Comment by nzw0301** [comment]
完全にどうでもいいことですが，

数学での距離は
- 非対称性
- 同一性
- 対称性
- 三角不等式

の4つを満たす必要があります．
KLダイバージェンスは，対称性と三角不等式を満たしませんので，厳密には距離ではありません．

**Comment by hururtoriya** [comment]
@nzw0301 
コメントありがとうございます!
確かに数学的には4つの性質を満たす必要がありますね。
@getumen さんの言い方的に、KLダイバージェンスを概念的にどう捉えるかというニュアンスで`距離`という言葉を選んだんじゃないのかなと思いました :smile:

**Comment by getumen** [comment]
@nzw0301 
ご指摘ありがとうございます。
距離の定義を満たしていませんね。
いい加減な説明でした。

**Comment by nzw0301** [comment]
@getumen 類似度的なニュアンスでおっしゃってるんだと思いましたのでおっしゃってることはわかります．”言語処理のための機械学習入門”でこの話題に触れていたので，コメントいたしました．
細かくてすみません...
