### ISSUE TITLE
#5 の発表内容

### ISSUE THREAD

**Issue by hururtoriya** [PRMLSeminar/prml-wakaranu#5]
PRML勉強会 6月の発表内容についてディスカッションしましょう :smile_cat: 

僕は、
- PRML(プレモル)本の2章の後半。 :book: 

本筋ではPRML本も勧めていきたいので、今回はこちらを優先しました。

- それ以外に本や論文について一つ何かしら喋りたい :bowtie: (7分) 

ハウスホルダー変換とQR分解については、後半の情報幾何が近づいたら解説することにします。
:octopus:

**Comment by jkfishlover** [comment]
私は以前お話したEMアルゴリズムについて、もう少し掘り下げて話そうと思います

**Comment by hururtoriya** [comment]
@jkfishlover :+1:  期待してます!
